// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fltpndxdtovgjuqarfsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdHBuZHhkdG92Z2p1cWFyZnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODc4OTAsImV4cCI6MjA2NzY2Mzg5MH0.EhUZnPoVoxo45XtkNQU8zZeioy_71pIMLxrGzMDHPdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});